<?php

declare(strict_types=1);

namespace Davix\Customs\Rule;

use Davix\Customs\Product\ProductCustomsDataInterface;

/**
 * One check against a product's customs data.
 *
 * The central abstraction of the whole product. A dashboard row is a rule with
 * a count. A grid filter is a rule code. A bulk fix is a rule's remediation. A
 * notification is a rule crossing a threshold. Adding a check is one class and
 * one registration - if it ever becomes more than that, the abstraction has
 * gone wrong and should be fixed before more checks are written.
 *
 * Implementations must be pure: no storage access, no network, no clock. The
 * evaluation date arrives in the context precisely so that a rule about
 * staleness is still a deterministic function of its inputs.
 */
interface RuleInterface
{
    /**
     * Stable machine identifier, e.g. 'withdrawn_code'.
     *
     * Persisted against issues and used in grid filters, so changing one is a
     * data migration rather than a rename.
     */
    public function code(): string;

    /**
     * The severity this rule emits by default.
     *
     * A merchant may override it in configuration; the rule neither knows nor
     * cares, and should always construct its issue with this value.
     */
    public function severity(): Severity;

    /**
     * Codes of rules that must pass before this one is worth running.
     *
     * Without this, one bad commodity code produces five issues on a single
     * product - unknown code, missing weight, ambiguous expansion and two
     * more - of which four are noise generated by the first. The merchant
     * fixes one thing and four issues vanish, which makes the counts look
     * arbitrary and the dashboard untrustworthy.
     *
     * A rule whose prerequisite emitted an issue is skipped, and skipping
     * cascades to anything depending on it in turn.
     *
     * @return list<string>
     */
    public function prerequisites(): array;

    /**
     * Examine one product. Return null when it passes.
     */
    public function evaluate(
        ProductCustomsDataInterface $data,
        EvaluationContext $context,
    ): ?Issue;
}
